export interface IJob  {
  _ownerId: string,
  companyName: string,
  positionName: string,
  positionCategory: string,
  employmentType: string,
  officePolicy: string,
  salary: string,
  location: string,
  description: string,
  responsibilities: string | string[],
  qualifications: string | string[],
  _createdOn: Date,
  _id: string,
  savedBy: string[],
}
