export const JOB_FORM_FIELDS = {
  COMPANY_NAME: 'companyName',
  POSITION_NAME: 'positionName',
  POSITION_CATEGORY: {
    SELECT_NAME: 'positionCategory',
    SELECTED_OPTION: 'Position Category',
    MARKETING: 'Marketing',
    HUMAN_RESOURCES: 'Human Resources',
    PROJECT_MANAGEMENT: 'Project Management',
    BUSINESS_DEVELOPMENT: 'Business Development',
    SALES_COMMUNICATION: 'Sales & Communication',
    TEACHING_EDUCATION: 'Teaching & Education',
    IT: 'IT',
    CUSTOMER_SERVICE: 'Customer Service',
  },
  EMPLOYMENT_TYPE: {
    SELECT_NAME: 'employmentType',
    SELECTED_OPTION: 'Employment Type',
    FULL_TIME: 'Full Time',
    PART_TIME: 'Part Time',
    INTERNSHIP: 'Internship',
    FREELANCE_PROJECT: 'Freelance/Project',
  },
  OFFICE_POLICY: {
    SELECT_NAME: 'officePolicy',
    SELECTED_OPTION: 'Office Policy',
    OFFICE: 'Office',
    HOME: 'Home',
    HYBRID: 'Hybrid',
  },
  SALARY: {
    SELECT_NAME: 'salary',
    SELECTED_OPTION: 'Salary Range',
    BELOW_20K: 'Below $20 000',
    BETWEEN_20K_39K: '$20 000 - $39 999',
    BETWEEN_40K_59K: '$40 000 - $59 999',
    BETWEEN_60K_79K: '$60 000 - $79 999',
    BETWEEN_80K_99K: '$80 000 - $99 999',
    ABOVE_100K: 'Above $100 000',
    CONFIDENTIAL: 'Confidential',
  },
  LOCATION: 'location',
  DESCRIPTION: 'description',
  RESPONSIBILITIES: 'responsibilities',
  QUALIFICATIONS: 'qualifications',
}
